[versions]
crate = "4.0.0-RC.2"
commandapi = "9.7.0"

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.2"
paper-api = "io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT"
morepaperlib = "space.arim.morepaperlib:morepaperlib:0.4.4"

# API dependencies
version-watch = "io.github.milkdrinkers:versionwatch:0.0.4"
crate-api = { module = "io.github.milkdrinkers:crate-api", version.ref = "crate" }
crate-yaml = { module = "io.github.milkdrinkers:crate-yaml", version.ref = "crate" }
colorparser = "io.github.milkdrinkers:colorparser:3.0.0"
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade", version.ref = "commandapi" }
commandapi-annotations = { module = "dev.jorel:commandapi-annotations", version.ref = "commandapi" }
triumph-gui = "dev.triumphteam:triumph-gui:3.1.11"

# Plugin dependencies
vault = "com.github.MilkBowl:VaultAPI:1.7.1"
placeholderapi = "me.clip:placeholderapi:2.11.6"

# Testing
junit-bom = "org.junit:junit-bom:5.12.1"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j = "org.slf4j:slf4j-simple:2.1.0-alpha1"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.20.6"
testcontainers-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]
testcontainers = ["testcontainers-jupiter", "testcontainers-mysql", "testcontainers-mariadb"]

[plugins]
shadow = "com.gradleup.shadow:8.3.6"
run-paper = "xyz.jpenilla.run-paper:2.3.1"
plugin-yml = "de.eldoria.plugin-yml.bukkit:0.7.1"