[versions]
crate = "4.0.0-RC.3"
commandapi = "10.1.1"

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.2"
paper-api = "io.papermc.paper:paper-api:1.21.5-R0.1-SNAPSHOT"

# API dependencies
crate-api = { module = "io.github.milkdrinkers:crate-api", version.ref = "crate" }
crate-yaml = { module = "io.github.milkdrinkers:crate-yaml", version.ref = "crate" }
colorparser = "io.github.milkdrinkers:colorparser:3.0.1"
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade", version.ref = "commandapi" }
commandapi-annotations = { module = "dev.jorel:commandapi-annotations", version.ref = "commandapi" }

# Plugin dependencies
itemsadder = "dev.lone:api-itemsadder:4.0.10"
nexo = "com.nexomc:nexo:1.10.0"
oraxen = "io.th0rgal:oraxen:1.192.0"
towny = "com.palmergames.bukkit.towny:towny:0.101.2.4"
worldedit = "com.sk89q.worldedit:worldedit-bukkit:7.4.0-SNAPSHOT"
boltbukkit = "org.popcraft:bolt-bukkit:1.1.79"
mmoitems = "net.Indyuce:MMOItems-API:6.10.1-SNAPSHOT"
mythiclib = "io.lumine:MythicLib-dist:1.7.1-SNAPSHOT"

# Testing
junit-bom = "org.junit:junit-bom:5.13.3"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j = "org.slf4j:slf4j-simple:2.1.0-alpha1"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.21.3"
testcontainers-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]
testcontainers = ["testcontainers-jupiter", "testcontainers-mysql", "testcontainers-mariadb"]

[plugins]
shadow = "com.gradleup.shadow:8.3.6"
run-paper = "xyz.jpenilla.run-paper:2.3.1"
plugin-yml = "de.eldoria.plugin-yml.bukkit:0.7.1"